### ISSUE TITLE
Repeated field is checked even if the main field is blank

### ISSUE THREAD

**Issue by BboyKeen** [boekkooi/JqueryValidationBundle#10]
Hi

I'm currently testing your bundle in my application.
I have a strange behaviour with a blank repeated field.

Here is the code to build my form

```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
        $builder
            ->add('username', null, array('label' => 'form.username', 'translation_domain' => 'FOSUserBundle'))
            ->add('email', 'email', array('label' => 'form.email', 'translation_domain' => 'FOSUserBundle'))
            ->add('plainPassword', 'repeated', array(
                'type' => 'password',
                'options' => array('translation_domain' => 'FOSUserBundle'),
                'first_options' => array('label' => 'form.password'),
                'second_options' => array('label' => 'form.password_confirmation'),
                'invalid_message' => 'fos_user.password.mismatch',
                'first_name' => 'password',
                'second_name' => 'password_repeated'
            ))
        ;
}
```

When I try to validate my form with client-side validation disabled, I got 
![form_server](https://cloud.githubusercontent.com/assets/1192309/8132660/9b5a3a64-1123-11e5-8216-f6bc9a73ed3a.png)

And with client-side validation enabled : 
![form_client](https://cloud.githubusercontent.com/assets/1192309/8132664/9f49902a-1123-11e5-9b5b-358a5a6a92e7.png)

I understand Symfony doesn't check the repeated field if the main field is blank whereas JQuery does.
Do you know how I can get the same result as Symfony ? Or even having the field considered as not correct.

By the way, I really like this bundle for saving me a lot of time.

Thanks

**Comment by boekkooi** [comment]
Hi @BboyKeen, 
Nice catch it seems that the [`equalTo`](https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Form/Rule/Processor/ValueToDuplicatesTransformerPass.php#L63) is validating correct (since it is). 

A quick way to fix this problem should be to use the `constraints` option in `second_options`.
```
    'second_options' => array(
        'label' => 'form.password_confirmation'
        'constraints' => array( new \Symfony\Component\Validator\Constraints\NotBlank() )
    ),
```

The actual problem here is more within jQueryValidate then within the bundle but it's confusing for sure. I will take a look at this once i have some spare time.

**Comment by BboyKeen** [comment]
Hi @boekkooi,
Thanks for your quick answer.
I was pretty sure jQuery validation was the reason but I preferred to ask.
I just tried what you suggest and it's fully working, so thanks again ;)

**Comment by boekkooi** [comment]
@BboyKeen If you don't mind using the latest dev-master then you won't need the quickfix any more.

**Comment by BboyKeen** [comment]
That sounds perfect. I will update immediately. Thanks.
