### ISSUE TITLE
Regex not working with jQuery validation 1.11 and 1.13

### ISSUE THREAD

**Issue by BboyKeen** [boekkooi/JqueryValidationBundle#11]
Hi again

Seems like Regex validation is not working.
I've activated the pattern option in the config but nothing happens in my browser.

I need to ensure the fields firstname and lastname are only letters. The other constraints works.

Here what I obtain in my browser's console :

![capture d ecran de 2015-06-12 18 47 02](https://cloud.githubusercontent.com/assets/1192309/8134953/a766d956-1133-11e5-83ed-c8c40636fbb5.png)

Perhaps it could help you.

**Comment by BboyKeen** [comment]
Having failed pattern validation introduces the possibility to submit the form even if the entered information is not right.

**Comment by boekkooi** [comment]
@BboyKeen can you double check that you are including the [additional-methods.js](https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Resources/public/additional-methods.js) in your page. (https://github.com/boekkooi/JqueryValidationBundle/blob/master/docs/usage.md#additional-rules) 
If this is the case then can you provide a example [gist](http://gist.github.com) with the form, data model (if any) and the template.

**Comment by BboyKeen** [comment]
@boekkooi You're right. I forgot to add the additional-method.js in my page. It's now fully working

Sorry for the inconvenience

**Comment by boekkooi** [comment]
No problem! I'm happy it works. If you have any more issue don't hesitate to report them.
