### ISSUE TITLE
Error in collection sample code

### ISSUE THREAD

**Issue by BboyKeen** [boekkooi/JqueryValidationBundle#12]
Hi

While I was trying to implement validation for my collection fields, I detected one mistake in the collection sample code you provide in the documentation.

I replaced 

`{%- set attr = attr|merge({'data-prototype': form_row(prototype) ~ '<script>' ~ form_jquery_validation(form) ~ '`**`<script>`**`' }) -%}`

by

` {%- set attr = attr|merge({'data-prototype': form_row(prototype) ~ '<script>' ~ form_jquery_validation(form) ~ '`**`</script>`**`' }) -%}`

to make it work. 

Do you confirm this is the way it should be ?

**Comment by boekkooi** [comment]
@BboyKeen Thanks for reporting!
