### ISSUE TITLE
Not working with jQuery 1.11

### ISSUE THREAD

**Issue by BboyKeen** [boekkooi/JqueryValidationBundle#13]
Hi Boekkooi,

Could you confirm your bundle isn't compatible with jQuery validate 1.11 ?

I have trouble using it with this version (undefined validator methods) and all my problems disappear with jQuery validate 1.13.

Thank you again

**Comment by boekkooi** [comment]
It is very well possible that the [`additional-methods.js`}(https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Resources/public/additional-methods.js) won't work with jQuery validate 1.11. I will check it out this weekend and get back to you.

Thanks for reporting :smile:

**Comment by BboyKeen** [comment]
My main problems appear with collections so you should dig into this first. 
I didn't see any other problem with jQuery validate 1.11.
But don't worry I can use the jQuery validate 1.13. :-)

**Comment by boekkooi** [comment]
I'm closing this since version 1.11 is not really update I have tested this lib with 1.13 and 1.14 so I can live with that. 

If you really/need want 1.11 support then please create a PR and I will merge it.

**Comment by BboyKeen** [comment]
I'm good with that too. I've updated to 1.13 since the issue.
Thanks for your support
