### ISSUE TITLE
Unable to set validation_groups dynamically depending on user input

### ISSUE THREAD

**Issue by rrajkomar** [boekkooi/JqueryValidationBundle#15]
It would be nice if we could have an option to dynamically change the validation_groups to use when validating the form depending on user inputs (i.e. : when using radio inputs)

**Comment by boekkooi** [comment]
Hey @rrajkomar 

This it possible with a little bit of extra code. 
Simply get the validator instance `var validator = $('form').validate();` and then enable or disable the needed groups using `validator.settings.validation_groups['<group_name>'] = true/false;`. I would advise to wrap this in a [`ready`](https://api.jquery.com/ready/) call so it is fired after the validator is instantiated. 

If you want and have the time you may create docs PR :smile:
