### ISSUE TITLE
Call to a member function getConfig() on a non-object

### ISSUE THREAD

**Issue by gaetan80** [boekkooi/JqueryValidationBundle#16]
JqueryValidationBundle is not working with that bundle : https://github.com/lexik/LexikMailerBundle

Error: Call to a member function getConfig() on a non-object
500 Internal Server Error - FatalErrorException

in vendor/boekkooi/jquery-validation-bundle/src/Form/FormDataConstraintFinder.php at line 117   -
        }
        // If the root inherits data, then grab the parent
        if ($dataForm->getConfig()->getInheritData()) {
            $dataForm = $dataForm->getParent();
        }

CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getConfig() on a non-object" at C:\wamp\www\...\vendor\boekkooi\jquery-validation-bundle\src\Form\FormDataConstraintFinder.php line 117 

Stack Trace (Plain Text)   -
[1] Symfony\Component\Debug\Exception\FatalErrorException: Error: Call to a member function getConfig() on a non-object
    at n/a
        in C:\wamp\www\...\vendor\boekkooi\jquery-validation-bundle\src\Form\FormDataConstraintFinder.php line 117

How to fix that ? Can I disable the validation on this form only?

**Comment by boekkooi** [comment]
Hi @gaetan80, 

You can disable the validation for just that form using the 'jquery_validation' option of the form (set it to false) `$this->createForm('my_type', null, array('jquery_validation' => false))`.

If you have the time should you maybe provide me with a gist of the form that is causing this problem?

Thanks for reporting!

**Comment by gaetan80** [comment]
Thanks! 

https://github.com/gaetan80/LexikMailerBundle/blob/master/Form/Type/EmailType.php
https://github.com/gaetan80/LexikMailerBundle/blob/master/Form/Handler/EmailFormHandler.php

**Comment by boekkooi** [comment]
So this bug is related to the not yet (fully) supported `property_path` I'm working on a fix but it ain't to easy. I will try and fix the bug this weekend (i hope)

**Comment by boekkooi** [comment]
@gaetan80 Please update to 'dev-master' and remove `'jquery_validation' => false` this should fix the problem. If this is not the case please reopen the issue. Thank very much for reporting!
