### ISSUE TITLE
create a form with an empty name.

### ISSUE THREAD

**Issue by aitboudad** [boekkooi/JqueryValidationBundle#17]
when I create a form without name JqueryValidationBundle produces 2 exceptions in:
 - https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Form/Util/FormHelper.php#L106
 - https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Form/FormDataConstraintFinder.php#L42

I made a quick fix for that see my commit 
https://github.com/aitboudad/JqueryValidationBundle/commit/da07b54201ff3b452c64e761e64f9970ed884724

```
$form = $this->get('form.factory')->createNamed('', new SimpleFormType());
```

**Comment by boekkooi** [comment]
Thank you for reporting! The problem should be fixed now (if not please reopen the issue).

**Comment by aitboudad** [comment]
@boekkooi There is still one issue in [FormDataConstraintFinder.php#L41](https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Form/FormDataConstraintFinder.php#L41) for [getPropertyPath](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Form.php#L222-L224) call

**Comment by boekkooi** [comment]
I just added the check but if you have the time could you provide me with the form + model that was able to get to that point to throw a exception?

**Comment by aitboudad** [comment]
Just edit `issue7Action` with 
```php
 $form = $this->get('form.factory')->createNamed('', new Issue7\Type\RecourseType());
```

```php
public function issue7Action(Request $request)
    {
        $resource = new Issue7\Model\Recourse();
        $resource->setContents(array(
            new Issue7\Model\Content(),
            new Issue7\Model\Content()
        ));
        $resource->setInvalidContents(array(
            new Issue7\Model\Content()
        ));

        $form = $this->get('form.factory')->createNamed('', new Issue7\Type\RecourseType());
        $form->setData($resource);
        $this->handleForm($request, $form);
        return $this->render('::form.html.twig', array('form' => $form->createView()));
    }
```
