### ISSUE TITLE
Error message in embedded collection

### ISSUE THREAD

**Issue by tomtoump** [boekkooi/JqueryValidationBundle#19]
Let's say I have these two entities:

```php
class Task
{
    /**
     * @Assert\NotBlank(message="You have to enter a task name")
     */
    protected $name;

    /**
     * @Assert\Valid()
     */
    protected $tags;
}
```

```php
class Tag
{
    /**
     * @Assert\NotBlank(message="You have to enter a tag name")
     */
    protected $name;
}
```

I also have a Task form which embeds a collection of Tags. 

The task name error is displayed correctly, but instead of the tag name error I get the generic "This field is required."

**Comment by boekkooi** [comment]
Hi @tomtoump 

I seem to be unable to reproduce this problem. Could you provide me with the form types that you are using and the symfony version?

Thank you for reporting!

**Comment by tomtoump** [comment]
```php
class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name');

        $builder->add('tags', 'collection', array(
            'type'         => new TagType(),
            'allow_add'    => true
        ));

        $builder->add('Save', 'submit');
    }

    ...
}
```

```php
class TagType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name');
    }

    ...
}
```

I'm using Symfony 2.7.3.

**Comment by boekkooi** [comment]
@tomtoump I'm still unable to reproduce this issue are you sure you are using the correct collection template that inject the extra JavaScript for a new tag? (see https://github.com/boekkooi/JqueryValidationBundle/blob/master/docs/usage.md#collection-prototype)

**Comment by tomtoump** [comment]
@boekkooi Sorry, I forgot to update the issue. 

It was my bad after all. I was already using the correct collection template. The issue was on my javascript that added a new element. 

Thanks for your support.
