### ISSUE TITLE
Validation with form row

### ISSUE THREAD

**Issue by yamiko-ninja** [boekkooi/JqueryValidationBundle#21]
`form_jquery_validation` replaces the `form` method. Can you do this for the other related twig methods like `form_start`, `form_end` and `form_row`?

**Comment by boekkooi** [comment]
Hi @yamiko-ninja Could you maybe explain a bit more about the issue/question because I don't know what you mean.

**Comment by yamiko-ninja** [comment]
In Symfony you can output the entire form with the `{{ form(form) }}` which uses a default form theme layout. If you want to control the overall layout without building a form theme their are other twig methods that can be used.

Here is an example using `form_row`s which generate the label, errors and input for an item in the form.

```twig
{{ form_start(form, { attr: {class: "validate", novalidate: "novalidate"}}) }}
    <div class="row">
        <div class="large-12 columns">
            {{ form_row(form.published) }}
        </div>
    </div>
    <div class="row">
        <div class="large-6 columns">
            {{ form_row(form.title) }}
        </div>
        <div class="large-6 columns">
            {{ form_row(form.slug) }}
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            {{ form_row(form.description) }}
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            {{ form_row(form.content) }}
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            {{ form_row(form.submit) }}
        </div>
    </div>
    {{ form_widget(form) }}
{{ form_end(form) }}
```
I am hoping that I could use your plugin in a similar manner but it looks like the only twig method is `form_jquery_validation` which is for the whole form.

**Comment by boekkooi** [comment]
Interesting idea. You can currently customize the the output by override the global templates for example [form_validate.js.twig](https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Resources/views/Form/form_validate.js.twig`) but there is no way to just render a single elements rules. 
Are you proposing to replace some of the macro's currently used with a twig method?

Also why exactly do you want this? Are you trying to exclude a element from rendering it's rules or is there some other reason to do this?

**Comment by boekkooi** [comment]
Closing issue because it's inactive. You can off course reopen it!
