### ISSUE TITLE
Assert\Regex validation check problem..  

### ISSUE THREAD

**Issue by feyyazesat** [boekkooi/JqueryValidationBundle#22]
Hi,
This is an amazing bundle it really saved my days thanks firstly. 
My Entity field has the following annotation https://gist.github.com/feyyazesat/aa6674271ce5174041ba

NotBlank and Length working properly. But when I write "xyaz 123" to the field, following errror appears on chrome dev console.

1c0764d-c181255_part_1_jquery.validate_2-2a98529.js:640 Uncaught TypeError: Cannot read property 'test' of null

Do you have any idea about this problem ?

**Comment by boekkooi** [comment]
Well since `/u` is not supported in JavaScript that is your problem (check you regex on for example https://regex101.com/#javascript). 
To fix this you can use the [`htmlPattern`](http://symfony.com/doc/current/reference/constraints/Regex.html#htmlpattern) to put in the correct JS version.

```
     * @Assert\Regex(
     *      pattern="/^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð']+$/u",
     *      htmlPattern="/^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð']+$/",
     *      match=true,
     *      message="user.form.validation.firstname.regex",
     *      groups = {"personal_info"}
     * )
```

**Comment by feyyazesat** [comment]
Perfect it solved my problem, I didn't know about javascript regex restrictions. Thanks.
