### ISSUE TITLE
Method "groups" does not exist

### ISSUE THREAD

**Issue by BboyKeen** [boekkooi/JqueryValidationBundle#24]
Hi Boekkoi,

Do you know what can cause this error ?
Method "groups" for object "Boekkooi\Bundle\JqueryValidationBundle\Form\Rule\TransformerRule" does not exist in BoekkooiJqueryValidationBundle:Form:macros.js.twig at line 49 

I think it has appeared after a composer update on dev-master.
I've tried with the 1.0.3 version, there is no problem.

Thank you

**Comment by boekkooi** [comment]
Hey @BboyKeen I'm not sure why this would happen can you provide me with the form and model?

**Comment by boekkooi** [comment]
Ok found the problem it was introduced in https://github.com/boekkooi/JqueryValidationBundle/commit/3cfc5b198f8ed7d2db5a69d24c0d048d70abbc16 Please update to the latest dev-master

Thanks for reporting!

**Comment by BboyKeen** [comment]
Thanks for the quick fix.
I'll give it a try at home.

**Comment by BboyKeen** [comment]
It's now fully working.

Thanks :)

**Comment by boekkooi** [comment]
No problem Thanks for reporting!
