### ISSUE TITLE
Please clarify doc about jquery_validation_groups

### ISSUE THREAD

**Issue by ohmer1** [boekkooi/JqueryValidationBundle#25]
I don't understand how I can use the bundle with validation groups.  I only get this exception: `Callable validation_groups are not supported. Disable jquery_validation or set jquery_validation_groups`.  

Googling `jquery_validation_groups` only returns the doc that say to set jquery_validation_groups... but where/how?

**Comment by ohmer1** [comment]
Found it.

**Comment by boekkooi** [comment]
Ok great if you have the time maybe you can extend the docs with some more information. I don't have the time at the moment but I would be happy to merge any documentation improvements.

**Comment by robertfausk** [comment]
@ohmer1 And where did you found it? I run into same problem :-/

**Comment by boekkooi** [comment]
Hi @robertfausk maybe taking a look at https://github.com/boekkooi/JqueryValidationBundle/blob/master/tests/Functional/TestBundle/Form/Type/ManualGroupsFormType.php will help you out.

**Comment by tonnyb** [comment]
Also found it very usefull to add validation_groups to the submit buttons, that worked for me.

**Comment by robertfausk** [comment]
Ok. I found where and how to place it in my *Type.php
My problem is now that the groups are not enabled in generated js. Only "Default" is enabled:

```JS
    ...
    validator.settings.validation_groups = {
        "app_registration": false,
        "app_registration_germany": false,
        "Default": false
    };
    form.find("*[name=\"app_userbundle_registration\x5Bsave\x5D\"]").click(function () {
        validator.settings.validation_groups = {
            "app_registration": false,
            "app_registration_germany": false,
            "Default": true
        };
    });
    ...
```

```PHP
// *Type.php
    ...
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'jquery_validation_groups' => array(
                self::VALIDATION_GROUP_REGISTRATION,
                self::VALIDATION_GROUP_REGISTRATION_GERMANY,
            ),
            'validation_groups' => function (FormInterface $form) {
                if ($form->getData() !== null && null !== $form->getData()->getContactCountry()) {
                    $country = $form->getData()->getContactCountry();
                    switch ($country) {
                        case '2':
                            return array(self::VALIDATION_GROUP_REGISTRATION_AUSTRIA);
                            break;
                        case '3':
                            return array(self::VALIDATION_GROUP_REGISTRATION_SWITZERLAND);
                            break;
                        case '4':
                            return array(self::VALIDATION_GROUP_REGISTRATION_ITALY);
                            break;
                        default:
                            return array(self::VALIDATION_GROUP_REGISTRATION_GERMANY);
                            break;
                    }
                } else {
                    return array(self::VALIDATION_GROUP_REGISTRATION);
                }
            },
            'data_class' => 'AppBundle\Entity\Registration'
        ));
    }
...
```

How is it possible to enable the other validation groups? Do I have to write some JS on my own?

PS: I'm willing to extend the doc after solving this.

**Comment by boekkooi** [comment]
@robertfausk could you please move your comment into a new issue because it looks related but is a different issue. You problem is that the validation groups are being excluded because there is no button that validates them. 

This can currently only be fixed by adding buttons that submit the form using a specific group or set of groups. So what we need is to add a 'jquery_validation_render_groups' option that will force a set of groups to be rendered in JS aka mark them as in use.
