### ISSUE TITLE
Use of unicode characters in RegExp

### ISSUE THREAD

**Issue by BboyKeen** [boekkooi/JqueryValidationBundle#26]
Hi Boekkooi,

When I use a pattern like : `/^[a-zA-Z0-9\\u00C0-]+$/` in Symfony constraint, it ends up in javascript in `[a-zA-Z\\\\u00C0-]` which is obviously not working.

Do you know any way to use unicode characters in RegExp constraints ?

Thanks

**Comment by boekkooi** [comment]
This seems very similar to #22

**Comment by BboyKeen** [comment]
You're right.

Looks like the same problem. 
I will try the given solution using unicode chars.
I just don't want to use hardcoded chars like in the code sample because of problems which can occur with different file encoding.

**Comment by BboyKeen** [comment]
Using the solution provided in #22, the validation is working.
I've used hardcoded chars for the moment. If it's a problem in the future, I'll reopen the issue.

Thanks again !

**Comment by boekkooi** [comment]
P.S. you should be able to use `/^[a-zA-Z0-9\u00C0\-]+$/` for the html pattern
