### ISSUE TITLE
Add validator constraint for Type

### ISSUE THREAD

**Issue by robertfausk** [boekkooi/JqueryValidationBundle#33]
http://symfony.com/doc/current/reference/constraints/Type.html

I don't know if its useful to implement the type constraint but currently I have a field with constraint Type and type is digit. It's for validating zip code.
A workaround would be to use Regex but Type feels better somehow.

**Comment by boekkooi** [comment]
@robertfausk If you want you can implement this your self and create a PR.

The rule that the Type constraint with [type](http://symfony.com/doc/current/reference/constraints/Type.html#reference-constraint-type-type) === 'digit' maps to is [digits](http://jqueryvalidation.org/digits-method).

So you can simply create a [Constraint Mapper](https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Form/Rule/ConstraintMapperInterface.php) that implements this case.
