### ISSUE TITLE
Add validator constraint for Length

### ISSUE THREAD

**Issue by robertfausk** [boekkooi/JqueryValidationBundle#35]
http://symfony.com/doc/current/reference/constraints/Length.html

It's currently not implemented and it would be fine to be able to use it :dancer:

**Comment by boekkooi** [comment]
Actually Length is implemented see https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Form/Rule/Mapping/MInLengthRule.php and https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Form/Rule/Mapping/MaxLengthRule.php

**Comment by robertfausk** [comment]
Hmm. It didn't work out of the box for me. I'll take a look and respond here.

**Comment by boekkooi** [comment]
@robertfausk If this is not working then please provide the FormType and DataClass :smile:

**Comment by boekkooi** [comment]
Closing ... Just reopen if you still have the issue
