### ISSUE TITLE
Deprecating warnings

### ISSUE THREAD

**Issue by horfic** [boekkooi/JqueryValidationBundle#37]
Hi,
first of all, thanks for the awesome library.

Is there a plan to fix all the deprecating warnings which are already showing up in sf 2.8.x.

PS: This should also help for easier compatibiliy to sf 3.x, when time comes.

best regards,
horfic

**Comment by boekkooi** [comment]
Hi @horfic,

The current plan on releasing a SF 3.0 version will be some where in the next month please follow PR #36 for more information when it is available.

Happy new years.

**Comment by boekkooi** [comment]
I'm closing this because the master branch now has support for Symfony 3 and where possible avoids deprecation warnings.
