### ISSUE TITLE
Required attribute removed

### ISSUE THREAD

**Issue by EAnushan** [boekkooi/JqueryValidationBundle#38]
I have a form I build using the following:
````
$builder
    ->add('user', UserType::class)
    ->add('consent', CheckboxType::class, [
        'required' => false,
    ]);
```

UserType contains a few fields, such as `firstName` and `lastName`. Both of these fields are required. When I enable this bundle, the `required` attributes on the inputs for `firstName` and `lastName` are removed.

This seems to be happening on `ValidConstraintPass` line 34. My form is not bound to an entity and it seems like `ValidConstraintPass` checks for `Symfony\Component\Validator\Constraints\Valid` on child form elements in the entity.

Do I need to bind my form to an entity and use the `@Valid` annotation to get your bundle to work?

**Comment by boekkooi** [comment]
@EAnushan this is correct the UserType can be null according to the validator this is why the required attribute is removed adding `['constraints' => new Valid() ]` or `['constraints' => new NotNull()]` to the 'user' field option should enable the required attribute again.

The reason for this behaviour is that symfony used to do some strange things for the required attribute.
(I'm not sure which issue this was related to but i think it was https://github.com/symfony/symfony/issues/3661)

**Comment by EAnushan** [comment]
Thank you. I ended up adding `['constraints' => new Valid() ]` to the `user` field and then adding additional constraints inside `UserType` so that each individual field was validated.
