### ISSUE TITLE
Validate subform

### ISSUE THREAD

**Issue by sintanial** [boekkooi/JqueryValidationBundle#7]
Hi, thx for greate bundle :).
I have a problem. I have form which contains another form\forms like this http://symfony.com/doc/current/cookbook/form/form_collections.html . How to validate subforms ?

**Comment by boekkooi** [comment]
Hi @sintanial,

Some quick questions:
- Are you constraints on the `data_class` or on the form type? if they are on the `data_class` don't forget to add the [Valid](http://symfony.com/doc/current/reference/constraints/Valid.html) constraint to you root `data_class` property.
- Are you using `allow_add` if so did you follow the instruction given here [Collection prototype](https://github.com/boekkooi/JqueryValidationBundle/blob/master/docs/usage.md#collection-prototype)?
- Is the failing Constraint the [Count](http://symfony.com/doc/current/reference/constraints/Count.html) constraint? If so then I'm sorry to say that it's not supported at the moment.

I hope this helps. If this won't fix your problem then please create a gist with the form types and data classes that you use so I can debug it and please tell me what Symfony version you are using.

Good luck!

**Comment by boekkooi** [comment]
@sintanial Where you able to get it to work?

**Comment by sintanial** [comment]
1. Added Valid constraint - still did not helped
2. No, i am not using allow_add
3. No. Is only 2 constraint: NotBlank, Length(min=3,max=10)

My code:

```php
// Recourse entity
class Recourse
{
//...
    /**
     * @var Content[]
     *
     * @Assert\Valid(deep = true)
     *
     * @ORM\OneToMany(targetEntity="Content", mappedBy="recourse")
     */
    private $contents;
}
```

```php
// Content entity
class Content
{
//...

    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\Length(min=3, max=8196)
     * @ORM\Column(name="message", type="text")
     */
    private $message;
}
```

Forms

```php
//RecourseType
class RecourseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //...
        $builder->add('contents', 'collection', [
            'type' => new ContentType,
            'options' => ['label' => false],
            'cascade_validation' => true,
            'label' => false,
        ]);
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(['data_class' => Recourse::class]);
    }

    public function getName()
    {
        return 'recourses';
    }
}
```

```php
//ContentType
class ContentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('message', 'textarea', [
            'attr' => ['placeholder' => 'Ваше сообщение']
        ]);
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(['data_class' => Content::class]);
    }


    public function getName()
    {
        return 'contents';
    }
}
```

**Comment by boekkooi** [comment]
@sintanial It is a bug! thanks for the example code! I'm going to try and fix it tonight

**Comment by sintanial** [comment]
oO ok, thx for the quick response )

**Comment by boekkooi** [comment]
@sintanial This should be fixed in dev-master
